CREATE STORAGE INTEGRATION olist_s3_integration
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::609898226012:role/olist_role'
    STORAGE_ALLOWED_LOCATIONS = ('s3://olistdbbucket/');

DESCRIBE INTEGRATION olist_s3_integration;

CREATE OR REPLACE FILE FORMAT OLIST_DB.RAW.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER =','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('','NULL','null')
    EMPTY_FIELD_AS_NULL  = TRUE;
CREATE OR REPLACE STAGE OLIST_DB.RAW.OLIST_S3_STAGE
    STORAGE_INTEGRATION = olist_s3_integration
    URL = 's3://olistdbbucket/raw/'
    FILE_FORMAT = (FORMAT_NAME = OLIST_DB.RAW.CSV_FORMAT);

LIST @OLIST_DB.RAW.OLIST_S3_STAGE;