{{
    config (
        post_hook= ["ALTER TABLE {{this}} ADD CONSTRAINT PK_DIM_CUSTOMERS PRIMARY KEY(CUSTOMER_ID) "]
    )
}}

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_UNIQUE_ID,
    C.CUSTOMER_ZIP_CODE_PREFIX,
    C.CUSTOMER_CITY,
    C.CUSTOMER_STATE,
    G.AVG_GEOLOCATION_LAT,
    G.AVG_GEOLOCATION_LNG
FROM {{ ref('stg_customers' )}} C 
LEFT JOIN {{ ref('stg_agg_geolocation')}} G
ON C.CUSTOMER_ZIP_CODE_PREFIX = G.GEOLOCATION_ZIP_CODE_PREFIX