
{{ config(
    post_hook=[
        "ALTER TABLE {{ this }} ADD CONSTRAINT PK_DIM_PRODUCTS PRIMARY KEY (PRODUCT_ID)"
    ]
) }}

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_CATEGORY_NAME PRODUCT_CATEGORY_NAME_PORTUGUESE,
    TR.PRODUCT_CATEGORY_NAME_ENGLISH,
    P.PRODUCT_PHOTOS_QTY,
    P.PRODUCT_WEIGHT_G,
    P.PRODUCT_LENGTH_CM,
    P.PRODUCT_HEIGHT_CM,
    P.PRODUCT_WIDTH_CM
FROM {{ ref('stg_products') }} P
LEFT JOIN {{ ref('stg_product_category_translation' )}} TR
ON P.PRODUCT_CATEGORY_NAME = TR.PRODUCT_CATEGORY_NAME