{{ config(
    post_hook=[
        "ALTER TABLE {{ this }} ADD CONSTRAINT PK_FACT_PAYMENTS PRIMARY KEY (ORDER_ID, PAYMENT_SEQUENTIAL)",
        "ALTER TABLE {{ this }} ADD CONSTRAINT FK_FACT_PAYMENTS_TYPE FOREIGN KEY (PAYMENT_TYPE_KEY) REFERENCES OLIST_DB.DBT_ANALYTICS.DIM_PAYMENT_TYPE(PAYMENT_TYPE_KEY)"
    ]
) }}
 
SELECT
    p.ORDER_ID,
    p.PAYMENT_SEQUENTIAL,
    pt.PAYMENT_TYPE_KEY,
    p.PAYMENT_INSTALLMENTS,
    p.PAYMENT_VALUE
FROM {{ ref('stg_order_payments') }} p
LEFT JOIN {{ ref('dim_payment_type') }} pt
    ON p.PAYMENT_TYPE = pt.PAYMENT_TYPE
 