{{ config(
    post_hook=[
        "ALTER TABLE {{ this }} ADD CONSTRAINT PK_FACT_ORDERS PRIMARY KEY (ORDER_ID, ORDER_ITEM_ID)",
        "ALTER TABLE {{ this }} ADD CONSTRAINT FK_FACT_ORDERS_CUSTOMERS FOREIGN KEY (CUSTOMER_ID) REFERENCES OLIST_DB.DBT_ANALYTICS.DIM_CUSTOMERS(CUSTOMER_ID)",
        "ALTER TABLE {{ this }} ADD CONSTRAINT FK_FACT_ORDERS_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES OLIST_DB.DBT_ANALYTICS.DIM_PRODUCTS(PRODUCT_ID)",
        "ALTER TABLE {{ this }} ADD CONSTRAINT FK_FACT_ORDERS_SELLERS FOREIGN KEY (SELLER_ID) REFERENCES OLIST_DB.DBT_ANALYTICS.DIM_SELLERS(SELLER_ID)",
        "ALTER TABLE {{ this }} ADD CONSTRAINT FK_FACT_ORDERS_PURCHASE_DATE FOREIGN KEY (PURCHASE_DATE_KEY) REFERENCES OLIST_DB.DBT_ANALYTICS.DIM_DATE(DATE_KEY)",
        "ALTER TABLE {{ this }} ADD CONSTRAINT FK_FACT_ORDERS_APPROVED_DATE FOREIGN KEY (APPROVED_DATE_KEY) REFERENCES OLIST_DB.DBT_ANALYTICS.DIM_DATE(DATE_KEY)",
        "ALTER TABLE {{ this }} ADD CONSTRAINT FK_FACT_ORDERS_DELIVERED_CARRIER_DATE FOREIGN KEY (DELIVERED_CARRIER_DATE_KEY) REFERENCES OLIST_DB.DBT_ANALYTICS.DIM_DATE(DATE_KEY)",
        "ALTER TABLE {{ this }} ADD CONSTRAINT FK_FACT_ORDERS_DELIVERED_CUSTOMER_DATE FOREIGN KEY (DELIVERED_CUSTOMER_DATE_KEY) REFERENCES OLIST_DB.DBT_ANALYTICS.DIM_DATE(DATE_KEY)",
        "ALTER TABLE {{ this }} ADD CONSTRAINT FK_FACT_ORDERS_ESTIMATED_DELIVERY_DATE FOREIGN KEY (ESTIMATED_DELIVERY_DATE_KEY) REFERENCES OLIST_DB.DBT_ANALYTICS.DIM_DATE(DATE_KEY)"
    ]
) }}


SELECT
    O.CUSTOMER_ID,
    OI.ORDER_ID,
    OI.ORDER_ITEM_ID,
    OI.PRODUCT_ID,
    OI.SELLER_ID,
    OI.PRICE,
    OI.FREIGHT_VALUE,
    O.ORDER_STATUS,
    
    {{to_date_key('O.ORDER_PURCHASE_TS')}} AS PURCHASE_DATE_KEY,
    {{to_date_key('O.ORDER_APPROVED_TS')}} AS APPROVED_DATE_KEY,
    {{to_date_key('O.ORDER_DELIVERED_CARRIER_DATE')}} AS DELIVERED_CARRIER_DATE_KEY,
    {{to_date_key('O.ORDER_DELIVERED_CUSTOMER_DATE')}} AS DELIVERED_CUSTOMER_DATE_KEY,
    {{to_date_key('O.ORDER_ESTIMATED_DELIVERY_DATE')}} AS ESTIMATED_DELIVERY_DATE_KEY,    
    
    DATEDIFF(day, O.ORDER_ESTIMATED_DELIVERY_DATE, O.ORDER_DELIVERED_CUSTOMER_DATE) AS DELIVERY_DELAY_DAYS


FROM {{ ref('stg_order_items') }} OI
JOIN {{ ref('stg_orders')}} O
ON O.ORDER_ID = OI.ORDER_ID