{{ config(
    post_hook=[
        "ALTER TABLE {{ this }} ADD CONSTRAINT PK_FACT_REVIEWS PRIMARY KEY (REVIEW_ID)",
        "ALTER TABLE {{ this }} ADD CONSTRAINT FK_FACT_REVIEWS_CREATION_DATE FOREIGN KEY (REVIEW_CREATION_DATE_KEY) REFERENCES OLIST_DB.DBT_ANALYTICS.DIM_DATE(DATE_KEY)",
        "ALTER TABLE {{ this }} ADD CONSTRAINT FK_FACT_REVIEWS_ANSWER_DATE FOREIGN KEY (REVIEW_ANSWER_DATE_KEY) REFERENCES OLIST_DB.DBT_ANALYTICS.DIM_DATE(DATE_KEY)"
    ]
) }}

SELECT
    REVIEW_ID,
    ORDER_ID,
    REVIEW_SCORE,
    {{ to_date_key('REVIEW_CREATION_DATE') }} AS REVIEW_CREATION_DATE_KEY,
    {{ to_date_key('REVIEW_ANSWER_TS') }}     AS REVIEW_ANSWER_DATE_KEY,
    REVIEW_COMMENT_TITLE,
    REVIEW_COMMENT_MESSAGE
FROM {{ ref('stg_order_reviews') }}