
SELECT
    PRODUCT_ID,
    PRODUCT_CATEGORY_NAME,
    TRY_CAST(PRODUCT_NAME_LENGHT AS INT) AS PRODUCT_NAME_LENGHT,
    TRY_CAST(PRODUCT_DESCRIPTION_LENGHT AS INT) AS PRODUCT_DESCRIPTION_LENGHT,
    TRY_CAST(PRODUCT_PHOTOS_QTY AS INT) AS PRODUCT_PHOTOS_QTY,
    TRY_TO_DECIMAL(PRODUCT_WEIGHT_G, 8, 2) AS PRODUCT_WEIGHT_G,
    TRY_TO_DECIMAL(PRODUCT_LENGTH_CM, 8, 2) AS PRODUCT_LENGTH_CM,
    TRY_TO_DECIMAL(PRODUCT_HEIGHT_CM, 8, 2) AS PRODUCT_HEIGHT_CM,
    TRY_TO_DECIMAL(PRODUCT_WIDTH_CM, 8, 2) AS PRODUCT_WIDTH_CM
FROM {{source('raw','products')}}