

SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    TRY_TO_TIMESTAMP(ORDER_PURCHASE_TIMESTAMP) AS ORDER_PURCHASE_TS,
    TRY_TO_TIMESTAMP(ORDER_APPROVED_AT) AS ORDER_APPROVED_TS,
    TRY_TO_DATE(ORDER_DELIVERED_CARRIER_DATE) AS ORDER_DELIVERED_CARRIER_DATE,
    TRY_TO_DATE(ORDER_DELIVERED_CUSTOMER_DATE) AS ORDER_DELIVERED_CUSTOMER_DATE,
    TRY_TO_DATE(ORDER_ESTIMATED_DELIVERY_DATE) AS ORDER_ESTIMATED_DELIVERY_DATE
FROM {{source('raw','orders')}}