
SELECT
    ORDER_ID,
    TRY_CAST(PAYMENT_SEQUENTIAL AS INT) AS PAYMENT_SEQUENTIAL,
    PAYMENT_TYPE,
    TRY_CAST(PAYMENT_INSTALLMENTS AS INT) AS PAYMENT_INSTALLMENTS,
    TRY_TO_DECIMAL(PAYMENT_VALUE, 10, 2) AS PAYMENT_VALUE
FROM  {{source('raw','order_payments')}}