SELECT
    REVIEW_ID,
    ORDER_ID,
    REVIEW_SCORE,
    TRY_TO_DATE(REVIEW_CREATION_DATE) AS REVIEW_CREATION_DATE,
    TRY_TO_TIMESTAMP(REVIEW_ANSWER_TIMESTAMP) AS REVIEW_ANSWER_TS,
    REVIEW_COMMENT_TITLE,
    REVIEW_COMMENT_MESSAGE
FROM {{ source('raw', 'order_reviews') }}
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY REVIEW_ID
    ORDER BY REVIEW_CREATION_DATE DESC
) = 1