
SELECT
    GEOLOCATION_ZIP_CODE_PREFIX,
    TRY_TO_DECIMAL(GEOLOCATION_LAT, 22, 18) AS GEOLOCATION_LAT,
    TRY_TO_DECIMAL(GEOLOCATION_LNG, 22, 18) AS GEOLOCATION_LNG,
    GEOLOCATION_CITY,
    GEOLOCATION_STATE
FROM {{source('raw','geolocation')}}