
SELECT 
    GEOLOCATION_ZIP_CODE_PREFIX,
    AVG(GEOLOCATION_LAT) AVG_GEOLOCATION_LAT,
    AVG(GEOLOCATION_LNG) AVG_GEOLOCATION_LNG
FROM {{ref('stg_geolocation')}}
GROUP BY  GEOLOCATION_ZIP_CODE_PREFIX