SELECT
    s.SELLER_ID,
    s.SELLER_CITY,
    s.SELLER_STATE,
    
    COUNT(f.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(f.PRODUCT_ID) AS TOTAL_PRODUCTS,
    
    SUM(f.PRICE) AS TOTAL_REVENUE,
    AVG(f.PRICE) AS AVG_ITEM_PRICE,
    SUM(f.FREIGHT_VALUE) AS TOTAL_FREIGHT,

    AVG(f.DELIVERY_DELAY_DAYS) AS AVG_DELIVERY_DELAY_DAYS,
    SUM(CASE WHEN (f.DELIVERY_DELAY_DAYS > 0 ) THEN 1 ELSE 0 END ) AS LATE_DELIVERIES,
    SUM(CASE WHEN (f.DELIVERY_DELAY_DAYS <= 0) THEN 1 ELSE 0 END ) AS ON_TIME_DELIVERIES,
    
    AVG(r.REVIEW_SCORE) AS AVG_REVIEW_SCORE,

    MODE(p.PRODUCT_CATEGORY_NAME_ENGLISH)  AS TOP_CATEGORY,

    MIN(d.DATE_DAY) AS FIRST_SALE_DATE,
    MAX(d.DATE_DAY) AS LAST_SALE_DATE,
    COUNT(DISTINCT d.YEAR || '-' || d.MONTH) AS ACTIVE_MONTHS

     

FROM {{ ref('fact_orders') }} f 
JOIN {{ ref('dim_sellers') }} s  
    ON f.SELLER_ID = s.SELLER_ID
LEFT JOIN {{ ref('fact_reviews') }} r
    ON f.ORDER_ID = r.ORDER_ID
LEFT JOIN {{ ref('dim_products') }} p
    ON f.PRODUCT_ID = p.PRODUCT_ID 
JOIN  {{ ref('dim_date') }} d
    ON f.PURCHASE_DATE_KEY = d.DATE_KEY

GROUP BY 
    s.SELLER_ID,
    s.SELLER_CITY,
    s.SELLER_STATE
