SELECT
    c.CUSTOMER_UNIQUE_ID,
    MODE(c.CUSTOMER_STATE) AS CUSTOMER_STATE,

    COUNT(fp.ORDER_ID) AS TOTAL_PAYMENT_RECORDS,
    SUM(fp.PAYMENT_VALUE)  AS TOTAL_AMOUNT_PAID,

    AVG(fp.PAYMENT_INSTALLMENTS) AS AVG_INSTALLMENTS,
    MAX(fp.PAYMENT_INSTALLMENTS) AS MAX_INSTALLMENTS_USED,
    CASE WHEN AVG(fp.PAYMENT_INSTALLMENTS) > 1
         THEN TRUE ELSE FALSE END  AS USES_INSTALLMENTS,

    MODE(pt.PAYMENT_TYPE) AS PREFERRED_PAYMENT_TYPE,

    SUM(CASE WHEN pt.PAYMENT_TYPE = 'credit_card'  THEN fp.PAYMENT_VALUE ELSE 0 END) AS CREDIT_CARD_SPEND,
    SUM(CASE WHEN pt.PAYMENT_TYPE = 'boleto'        THEN fp.PAYMENT_VALUE ELSE 0 END) AS BOLETO_SPEND,
    SUM(CASE WHEN pt.PAYMENT_TYPE = 'voucher'       THEN fp.PAYMENT_VALUE ELSE 0 END) AS VOUCHER_SPEND,
    SUM(CASE WHEN pt.PAYMENT_TYPE = 'debit_card'   THEN fp.PAYMENT_VALUE ELSE 0 END) AS DEBIT_CARD_SPEND,

    CASE WHEN SUM(CASE WHEN pt.PAYMENT_TYPE = 'voucher' THEN 1 ELSE 0 END) > 0
         THEN TRUE ELSE FALSE END                                           AS USES_VOUCHERS

FROM {{ ref('fact_payments') }} fp
JOIN {{ ref('fact_orders') }} fo
    ON fp.ORDER_ID = fo.ORDER_ID
JOIN {{ ref('dim_customers') }} c
    ON fo.CUSTOMER_ID = c.CUSTOMER_ID
JOIN {{ ref('dim_payment_type') }} pt
    ON fp.PAYMENT_TYPE_KEY = pt.PAYMENT_TYPE_KEY
GROUP BY
    c.CUSTOMER_UNIQUE_ID