SELECT
    c.CUSTOMER_UNIQUE_ID,
    MODE(c.CUSTOMER_STATE) AS CUSTOMER_STATE,
    MODE(c.CUSTOMER_CITY) AS CUSTOMER_CITY,

    COUNT(DISTINCT f.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(f.ORDER_ITEM_ID) AS TOTAL_ITEMS_PURCHASED,

    SUM(f.PRICE) AS LIFETIME_VALUE,
    AVG(f.PRICE)  AS AVG_ORDER_ITEM_VALUE,
    SUM(f.FREIGHT_VALUE) AS TOTAL_FREIGHT_PAID,


    MIN(d.DATE_DAY) AS FIRST_ORDER_DATE,
    MAX(d.DATE_DAY) AS LAST_ORDER_DATE,
    DATEDIFF(day, MAX(d.DATE_DAY), '{{ var("latest_date") }}')  AS DAYS_SINCE_LAST_ORDER,

    AVG(f.DELIVERY_DELAY_DAYS) AS AVG_DELIVERY_DELAY_DAYS,
    SUM(CASE WHEN f.DELIVERY_DELAY_DAYS <= 0 THEN 1 ELSE 0 END)  AS ON_TIME_DELIVERIES,
    SUM(CASE WHEN f.DELIVERY_DELAY_DAYS > 0 THEN 1 ELSE 0 END) AS LATE_DELIVERIES,


    AVG(r.REVIEW_SCORE) AS AVG_REVIEW_SCORE,

    CASE
        WHEN DATEDIFF(day, MAX(d.DATE_DAY), '{{ var("latest_date") }}') > 180
        THEN TRUE ELSE FALSE
    END  AS IS_CHURNED

FROM {{ ref('fact_orders') }} f
JOIN {{ ref('dim_customers') }} c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
JOIN {{ ref('dim_date') }} d
    ON f.PURCHASE_DATE_KEY = d.DATE_KEY
LEFT JOIN {{ ref('fact_reviews') }} r
    ON f.ORDER_ID = r.ORDER_ID
GROUP BY
    c.CUSTOMER_UNIQUE_ID