SELECT
    COALESCE(p.PRODUCT_CATEGORY_NAME_ENGLISH, 'Uncategorized') AS CATEGORY,

    COUNT(DISTINCT f.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(f.ORDER_ITEM_ID) AS TOTAL_UNITS_SOLD,

    SUM(f.PRICE) AS TOTAL_REVENUE,
    AVG(f.PRICE) AS AVG_ITEM_PRICE,
    SUM(f.FREIGHT_VALUE) AS TOTAL_FREIGHT,
    ROUND(AVG(f.FREIGHT_VALUE / NULLIF(f.PRICE, 0)) * 100, 2) AS AVG_FREIGHT_TO_PRICE_PCT,

    AVG(r.REVIEW_SCORE) AS AVG_REVIEW_SCORE,

    AVG(f.DELIVERY_DELAY_DAYS) AS AVG_DELIVERY_DELAY_DAYS,

    AVG(p.PRODUCT_WEIGHT_G)AS AVG_WEIGHT_G,
    AVG(p.PRODUCT_PHOTOS_QTY) AS AVG_PHOTOS_QTY

FROM {{ ref('fact_orders') }} f
JOIN {{ ref('dim_products') }} p
    ON f.PRODUCT_ID = p.PRODUCT_ID
LEFT JOIN {{ ref('fact_reviews') }} r
    ON f.ORDER_ID = r.ORDER_ID
GROUP BY
    COALESCE(p.PRODUCT_CATEGORY_NAME_ENGLISH, 'Uncategorized')
ORDER BY TOTAL_REVENUE DESC
