

CREATE OR REPLACE PROCEDURE CHECK_NULLS(TABLE_NAME STRING, COLUMN_NAME STRING)
RETURNS TABLE(TOTAL INT , SUCCESSFUL_CAST INT ,FAILED_CAST INT)
LANGUAGE SQL
AS 
$$
DECLARE 
    query STRING;
    res RESULTSET;
BEGIN
    query := 'SELECT COUNT(*) AS TOTAL, ' ||
             'COUNT(' || :COLUMN_NAME || ') AS SUCCESSFUL_CAST, ' ||
             'COUNT(*) - COUNT(' || :COLUMN_NAME || ') AS FAILED_CAST ' ||
             'FROM ' || :TABLE_NAME || ';';
    
    res := (EXECUTE IMMEDIATE :query);
    RETURN TABLE(res);
END;
$$;

