USE DATABASE OLIST_DB;

CREATE SCHEMA OLIST_DB.STAGING;

USE SCHEMA OLIST_DB.STAGING;

CREATE OR REPLACE VIEW OLIST_DB.STAGING.STG_ORDERS
AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    TRY_TO_TIMESTAMP(ORDER_PURCHASE_TIMESTAMP) AS ORDER_PURCHASE_TS,
    TRY_TO_TIMESTAMP(ORDER_APPROVED_AT) AS ORDER_APPROVED_TS,
    TRY_TO_TIMESTAMP(ORDER_DELIVERED_CARRIER_DATE) AS ORDER_DELIVERED_CARRIER_TS,
    TRY_TO_TIMESTAMP(ORDER_DELIVERED_CUSTOMER_DATE) AS ORDER_DELIVERED_CUSTOMER_TS,
    TRY_TO_DATE(ORDER_ESTIMATED_DELIVERY_DATE) AS ORDER_ESTIMATED_DELIVERY_DATE
FROM OLIST_DB.RAW.ORDERS;


CREATE OR REPLACE VIEW OLIST_DB.STAGING.STG_ORDER_ITEMS
AS
SELECT
    ORDER_ID,
    ORDER_ITEM_ID,
    PRODUCT_ID,
    SELLER_ID,
    TRY_TO_DECIMAL(PRICE, 10, 3) AS PRICE,
    TRY_TO_DECIMAL(FREIGHT_VALUE, 10, 3) AS FREIGHT_VALUE
FROM OLIST_DB.RAW.ORDER_ITEMS;

CREATE OR REPLACE VIEW OLIST_DB.STAGING.STG_ORDER_REVIEWS
AS
SELECT
    REVIEW_ID,
    ORDER_ID,
    TRY_CAST(REVIEW_SCORE AS INT) AS REVIEW_SCORE,
    REVIEW_COMMENT_TITLE,
    REVIEW_COMMENT_MESSAGE,
    TRY_TO_DATE(REVIEW_CREATION_DATE) AS REVIEW_CREATION_DATE,
    TRY_TO_TIMESTAMP(REVIEW_ANSWER_TIMESTAMP) AS REVIEW_ANSWER_TS
FROM OLIST_DB.RAW.ORDER_REVIEWS;


CREATE OR REPLACE VIEW OLIST_DB.STAGING.STG_CUSTOMERS
AS
SELECT *
FROM OLIST_DB.RAW.CUSTOMERS;


CREATE OR REPLACE VIEW OLIST_DB.STAGING.STG_GEOLOCATION
AS
SELECT
    GEOLOCATION_ZIP_CODE_PREFIX,
    TRY_TO_DECIMAL(GEOLOCATION_LAT, 21, 18) AS GEOLOCATION_LAT,
    TRY_TO_DECIMAL(GEOLOCATION_LNG, 21, 18) AS GEOLOCATION_LNG,
    GEOLOCATION_CITY,
    GEOLOCATION_STATE
FROM OLIST_DB.RAW.GEOLOCATION;

CREATE OR REPLACE VIEW OLIST_DB.STAGING.STG_PRODUCTS
AS
SELECT
    PRODUCT_ID,
    PRODUCT_CATEGORY_NAME,
    TRY_CAST(PRODUCT_NAME_LENGHT AS INT) AS PRODUCT_NAME_LENGHT,
    TRY_CAST(PRODUCT_DESCRIPTION_LENGHT AS INT) AS PRODUCT_DESCRIPTION_LENGHT,
    TRY_CAST(PRODUCT_PHOTOS_QTY AS INT) AS PRODUCT_PHOTOS_QTY,
    TRY_TO_DECIMAL(PRODUCT_WEIGHT_G, 8, 2) AS PRODUCT_WEIGHT_G,
    TRY_TO_DECIMAL(PRODUCT_LENGTH_CM, 8, 2) AS PRODUCT_LENGTH_CM,
    TRY_TO_DECIMAL(PRODUCT_HEIGHT_CM, 8, 2) AS PRODUCT_HEIGHT_CM,
    TRY_TO_DECIMAL(PRODUCT_WIDTH_CM, 8, 2) AS PRODUCT_WIDTH_CM
FROM OLIST_DB.RAW.PRODUCTS;

CREATE OR REPLACE VIEW OLIST_DB.STAGING.STG_SELLERS
AS
SELECT *
FROM OLIST_DB.RAW.SELLERS;

CREATE OR REPLACE VIEW OLIST_DB.STAGING.STG_PRODUCT_CATEGORY_TRANSLATION
AS
SELECT *
FROM OLIST_DB.RAW.PRODUCT_CATEGORY_TRANSLATION;

CREATE OR REPLACE VIEW OLIST_DB.STAGING.STG_ORDER_PAYMENTS
AS
SELECT
    ORDER_ID,
    TRY_CAST(PAYMENT_SEQUENTIAL AS INT) AS PAYMENT_SEQUENTIAL,
    PAYMENT_TYPE,
    TRY_CAST(PAYMENT_INSTALLMENTS AS INT) AS PAYMENT_INSTALLMENTS,
    TRY_TO_DECIMAL(PAYMENT_VALUE, 10, 2) AS PAYMENT_VALUE
FROM OLIST_DB.RAW.ORDER_PAYMENTS;
