USE DATABASE OLIST_DB;
USE SCHEMA OLIST_DB.RAW;

CREATE VIEW OLIST_DB.RAW.ORDERS_DEBUG
AS
SELECT 
    ORDER_ID,
    CUSTOMER_ID ,
    ORDER_STATUS,
    TRY_TO_TIMESTAMP(ORDER_PURCHASE_TIMESTAMP) AS ORDER_PURCHASE_TS,
    TRY_TO_TIMESTAMP(ORDER_APPROVED_AT) AS ORDER_APPROVED_TS,
    TRY_TO_TIMESTAMP(ORDER_DELIVERED_CARRIER_DATE) AS ORDER_DELIVERED_CARRIER_TS,
    TRY_TO_TIMESTAMP(ORDER_DELIVERED_CARRIER_DATE) AS ORDER_DELIVERED_CUSTOMER_TS,
    TRY_TO_DATE(ORDER_ESTIMATED_DELIVERY_DATE) AS ORDER_ESTIMATED_DELIVERY_DATE
FROM OLIST_DB.RAW.ORDERS;


CREATE OR REPLACE VIEW ORDER_ITEMS_DEBUG
AS
SELECT 
    ORDER_ID,
    ORDER_ITEM_ID,
    PRODUCT_ID,
    SELLER_ID,
    TRY_TO_DECIMAL(PRICE , 12,10) PRICE,
    TRY_TO_DECIMAL(FREIGHT_VALUE , 12, 10) FREIGHT_VALUE
FROM ORDER_ITEMS;



CREATE OR REPLACE VIEW ORDER_VIEW_DEBUG
AS
SELECT 
    REVIEW_ID,
    ORDER_ID,
    TRY_CAST(REVIEW_SCORE AS INT) REVIEW_SCORE,
    REVIEW_COMMENT_TITLE,
    REVIEW_COMMENT_MESSAGE,
    TRY_TO_DATE(REVIEW_CREATION_DATE) REVIEW_CREATION_DATE,
    TRY_TO_TIMESTAMP(REVIEW_ANSWER_TIMESTAMP) REVIEW_ANSWER_TS
FROM ORDER_REVIEWS;


CREATE OR REPLACE VIEW CUSTOMER_DEBUG
AS 
SELECT *
FROM CUSTOMERS;



CREATE OR REPLACE VIEW GEOLOCATION_DEBUG
AS
SELECT 
    GEOLOCATION_ZIP_CODE_PREFIX,
    TRY_TO_DECIMAL(GEOLOCATION_LAT , 20,18) AS GEOLOCATION_LAT,
    TRY_TO_DECIMAL(GEOLOCATION_LNG , 20,18) AS GEOLOCATION_LNG,
    GEOLOCATION_CITY,
    GEOLOCATION_STATE
FROM GEOLOCATION;

SELECT * FROM PRODUCTS
LIMIT 5;


CREATE OR REPLACE VIEW PRODUCTS_DEBUG
AS 
SELECT 
    PRODUCT_ID,
    PRODUCT_CATEGORY_NAME,
    TRY_CAST(PRODUCT_NAME_LENGHT AS INT) PRODUCT_NAME_LENGHT,
    TRY_CAST(PRODUCT_DESCRIPTION_LENGHT AS INT) PRODUCT_DESCRIPTION_LENGHT,
    TRY_CAST(PRODUCT_PHOTOS_QTY AS INT) PRODUCT_PHOTOS_QTY,
    TRY_TO_DECIMAL(PRODUCT_WEIGHT_G , 8 ,2) PRODUCT_WEIGHT_G,
    TRY_TO_DECIMAL(PRODUCT_LENGTH_CM , 8 ,2) PRODUCT_LENGTH_CM,
    TRY_TO_DECIMAL(PRODUCT_HEIGHT_CM , 8 ,2) PRODUCT_HEIGHT_CM,
    TRY_TO_DECIMAL(PRODUCT_WIDTH_CM , 8 ,2) PRODUCT_WIDTH_CM
FROM PRODUCTS;


CREATE OR REPLACE VIEW SELLERS_DEBUG
AS
SELECT *
FROM SELLERS;


CREATE OR REPLACE VIEW PRODUCT_CATEGORY_TRANSLATION_DEBUG
AS
SELECT *
FROM PRODUCT_CATEGORY_TRANSLATION;

SELECT * 
FROM ORDER_PAYMENTS
LIMIT 5;

CREATE OR REPLACE VIEW ORDER_PAYMENTS_DEBUG
AS 
SELECT
    ORDER_ID,
    TRY_CAST(PAYMENT_SEQUENTIAL AS INT) PAYMENT_SEQUENTIAL,
    PAYMENT_TYPE,
    TRY_CAST(PAYMENT_INSTALLMENTS AS INT) PAYMENT_INSTALLMENTS,
    TRY_TO_DECIMAL(PAYMENT_VALUE , 10 , 2) PAYMENT_VALUE
FROM ORDER_PAYMENTS;

SHOW VIEWS;