



//Business question: who are our best customers and who are the customers we lost?
// since i wanna compare the last time a customer ordered something , using current_date() doesn t make a sense in a static database , so i used the latest date we made a delivery
SET LATEST_DATE = '2018-10-17'; 
CREATE OR REPLACE TABLE OLIST_DB.ANALYTICS.MART_CUSTOMER_LTV_CHURN AS
SELECT
    c.CUSTOMER_UNIQUE_ID,
    c.CUSTOMER_STATE,
    c.CUSTOMER_CITY,
    c.AVG_GEOLOCATION_LAT,
    c.AVG_GEOLOCATION_LNG,

    COUNT(DISTINCT f.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(f.ORDER_ITEM_ID) AS TOTAL_ITEMS_PURCHASED,

    SUM(f.PRICE) AS LIFETIME_VALUE,
    AVG(f.PRICE)  AS AVG_ORDER_ITEM_VALUE,
    SUM(f.FREIGHT_VALUE) AS TOTAL_FREIGHT_PAID,


    MIN(d.DATE_DAY) AS FIRST_ORDER_DATE,
    MAX(d.DATE_DAY) AS LAST_ORDER_DATE,
    DATEDIFF(day, MAX(d.DATE_DAY), $LATEST_DATE)  AS DAYS_SINCE_LAST_ORDER,

    AVG(f.DELIVERY_DELAY_DAYS) AS AVG_DELIVERY_DELAY_DAYS,
    SUM(CASE WHEN f.DELIVERY_DELAY_DAYS <= 0 THEN 1 ELSE 0 END)  AS ON_TIME_DELIVERIES,
    SUM(CASE WHEN f.DELIVERY_DELAY_DAYS > 0 THEN 1 ELSE 0 END) AS LATE_DELIVERIES,


    AVG(r.REVIEW_SCORE) AS AVG_REVIEW_SCORE,

    CASE
        WHEN DATEDIFF(day, MAX(d.DATE_DAY), $LATEST_DATE) > 180
        THEN TRUE ELSE FALSE
    END  AS IS_CHURNED

FROM OLIST_DB.ANALYTICS.FACT_ORDERS f
JOIN OLIST_DB.ANALYTICS.DIM_CUSTOMERS c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
JOIN OLIST_DB.ANALYTICS.DIM_DATE d
    ON f.PURCHASE_DATE_KEY = d.DATE_KEY
LEFT JOIN OLIST_DB.ANALYTICS.FACT_REVIEWS r
    ON f.ORDER_ID = r.ORDER_ID
GROUP BY
    c.CUSTOMER_UNIQUE_ID,
    c.CUSTOMER_STATE,
    c.CUSTOMER_CITY,
    c.AVG_GEOLOCATION_LAT,
    c.AVG_GEOLOCATION_LNG;



// Business question: which of our sellers are reliable and high value?
CREATE OR REPLACE TABLE OLIST_DB.ANALYTICS.MART_SELLER_PERFORMANCE AS
SELECT
    s.SELLER_ID,
    s.SELLER_CITY,
    s.SELLER_STATE,
    
    COUNT(f.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(f.PRODUCT_ID) AS TOTAL_PRODUCTS,
    
    SUM(f.PRICE) AS TOTAL_REVENUE,
    AVG(f.PRICE) AS AVG_ITEM_PRICE,
    SUM(f.FREIGHT_VALUE) AS TOTAL_FREIGHT,

    AVG(f.DELIVERY_DELAY_DAYS) AS AVG_DELIVERY_DELAY_DAYS,
    SUM(CASE WHEN (f.DELIVERY_DELAY_DAYS > 0 ) THEN 1 ELSE 0 END ) AS LATE_DELIVERIES,
    SUM(CASE WHEN (f.DELIVERY_DELAY_DAYS <= 0) THEN 1 ELSE 0 END ) AS ON_TIME_DELIVERIES,
    
    AVG(r.REVIEW_SCORE) AS AVG_REVIEW_SCORE,

    MODE(p.PRODUCT_CATEGORY_NAME_ENGLISH)  AS TOP_CATEGORY,

    MIN(d.DATE_DAY) AS FIRST_SALE_DATE,
    MAX(d.DATE_DAY) AS LAST_SALE_DATE,
    COUNT(DISTINCT d.YEAR || '-' || d.MONTH) AS ACTIVE_MONTHS

     

FROM OLIST_DB.ANALYTICS.FACT_ORDERS f 
JOIN OLIST_DB.ANALYTICS.DIM_SELLERS s  
    ON f.SELLER_ID = s.SELLER_ID
LEFT JOIN OLIST_DB.ANALYTICS.FACT_REVIEWS r
    ON f.ORDER_ID = r.ORDER_ID
LEFT JOIN OLIST_DB.ANALYTICS.DIM_PRODUCTS p
    ON f.PRODUCT_ID = p.PRODUCT_ID 
JOIN  OLIST_DB.ANALYTICS.DIM_DATE d
    ON f.PURCHASE_DATE_KEY = d.DATE_KEY

GROUP BY 
    s.SELLER_ID,
    s.SELLER_CITY,
    s.SELLER_STATE;


// Business question: which categories drive revenue and satisfaction?

CREATE OR REPLACE TABLE OLIST_DB.ANALYTICS.MART_PRODUCT_CATEGORY_PERFORMANCE AS
SELECT
    COALESCE(p.PRODUCT_CATEGORY_NAME_ENGLISH, 'Uncategorized') AS CATEGORY,

    COUNT(DISTINCT f.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(f.ORDER_ITEM_ID) AS TOTAL_UNITS_SOLD,

    SUM(f.PRICE) AS TOTAL_REVENUE,
    AVG(f.PRICE) AS AVG_ITEM_PRICE,
    SUM(f.FREIGHT_VALUE) AS TOTAL_FREIGHT,
    ROUND(AVG(f.FREIGHT_VALUE / NULLIF(f.PRICE, 0)) * 100, 2) AS AVG_FREIGHT_TO_PRICE_PCT,

    AVG(r.REVIEW_SCORE) AS AVG_REVIEW_SCORE,

    AVG(f.DELIVERY_DELAY_DAYS) AS AVG_DELIVERY_DELAY_DAYS,

    AVG(p.PRODUCT_WEIGHT_G)AS AVG_WEIGHT_G,
    AVG(p.PRODUCT_PHOTOS_QTY) AS AVG_PHOTOS_QTY

FROM OLIST_DB.ANALYTICS.FACT_ORDERS f
JOIN OLIST_DB.ANALYTICS.DIM_PRODUCTS p
    ON f.PRODUCT_ID = p.PRODUCT_ID
LEFT JOIN OLIST_DB.ANALYTICS.FACT_REVIEWS r
    ON f.ORDER_ID = r.ORDER_ID
GROUP BY
    COALESCE(p.PRODUCT_CATEGORY_NAME_ENGLISH, 'Uncategorized')
ORDER BY TOTAL_REVENUE DESC;



// Business question: how do customers prefer to pay?

CREATE OR REPLACE TABLE OLIST_DB.ANALYTICS.MART_PAYMENT_BEHAVIOR AS
SELECT
    c.CUSTOMER_UNIQUE_ID,
    c.CUSTOMER_STATE,

    COUNT(fp.ORDER_ID) AS TOTAL_PAYMENT_RECORDS,
    SUM(fp.PAYMENT_VALUE)  AS TOTAL_AMOUNT_PAID,

    AVG(fp.PAYMENT_INSTALLMENTS) AS AVG_INSTALLMENTS,
    MAX(fp.PAYMENT_INSTALLMENTS) AS MAX_INSTALLMENTS_USED,
    CASE WHEN AVG(fp.PAYMENT_INSTALLMENTS) > 1
         THEN TRUE ELSE FALSE END  AS USES_INSTALLMENTS,

    MODE(pt.PAYMENT_TYPE) AS PREFERRED_PAYMENT_TYPE,

    SUM(CASE WHEN pt.PAYMENT_TYPE = 'credit_card'  THEN fp.PAYMENT_VALUE ELSE 0 END) AS CREDIT_CARD_SPEND,
    SUM(CASE WHEN pt.PAYMENT_TYPE = 'boleto'        THEN fp.PAYMENT_VALUE ELSE 0 END) AS BOLETO_SPEND,
    SUM(CASE WHEN pt.PAYMENT_TYPE = 'voucher'       THEN fp.PAYMENT_VALUE ELSE 0 END) AS VOUCHER_SPEND,
    SUM(CASE WHEN pt.PAYMENT_TYPE = 'debit_card'   THEN fp.PAYMENT_VALUE ELSE 0 END) AS DEBIT_CARD_SPEND,

    CASE WHEN SUM(CASE WHEN pt.PAYMENT_TYPE = 'voucher' THEN 1 ELSE 0 END) > 0
         THEN TRUE ELSE FALSE END                                           AS USES_VOUCHERS

FROM OLIST_DB.ANALYTICS.FACT_PAYMENTS fp
JOIN OLIST_DB.ANALYTICS.FACT_ORDERS fo
    ON fp.ORDER_ID = fo.ORDER_ID
JOIN OLIST_DB.ANALYTICS.DIM_CUSTOMERS c
    ON fo.CUSTOMER_ID = c.CUSTOMER_ID
JOIN OLIST_DB.ANALYTICS.DIM_PAYMENT_TYPE pt
    ON fp.PAYMENT_TYPE_KEY = pt.PAYMENT_TYPE_KEY
GROUP BY
    c.CUSTOMER_UNIQUE_ID,
    c.CUSTOMER_STATE;
