CREATE SCHEMA OLIST_DB.ANALYTICS;


// creating a geolocation view to group them by zip code since the exact coordinations arent necessary

CREATE OR REPLACE VIEW OLIST_DB.STAGING.STG_GEOLOCATION_AGG
AS
SELECT 
    GEOLOCATION_ZIP_CODE_PREFIX,
    AVG(GEOLOCATION_LAT) AVG_GEOLOCATION_LAT,
    AVG(GEOLOCATION_LNG) AVG_GEOLOCATION_LNG
FROM OLIST_DB.STAGING.STG_GEOLOCATION
GROUP BY 
    GEOLOCATION_ZIP_CODE_PREFIX;

// creating the dims

CREATE OR REPLACE TABLE OLIST_DB.ANALYTICS.DIM_PRODUCTS
AS 
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_CATEGORY_NAME PRODUCT_CATEGORY_NAME_PORTUGUESE,
    TR.PRODUCT_CATEGORY_NAME_ENGLISH,
    P.PRODUCT_PHOTOS_QTY,
    P.PRODUCT_WEIGHT_G,
    P.PRODUCT_LENGTH_CM,
    P.PRODUCT_HEIGHT_CM,
    P.PRODUCT_WIDTH_CM
FROM OLIST_DB.STAGING.STG_PRODUCTS P
LEFT JOIN OLIST_DB.STAGING.STG_PRODUCT_CATEGORY_TRANSLATION TR
ON P.PRODUCT_CATEGORY_NAME = TR.PRODUCT_CATEGORY_NAME;

ALTER TABLE OLIST_DB.ANALYTICS.DIM_PRODUCTS
ADD CONSTRAINT PK_DIM_PRODUCTS PRIMARY KEY (PRODUCT_ID);


CREATE OR REPLACE TABLE OLIST_DB.ANALYTICS.DIM_CUSTOMERS
AS
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_UNIQUE_ID,
    C.CUSTOMER_ZIP_CODE_PREFIX,
    C.CUSTOMER_CITY,
    C.CUSTOMER_STATE,
    G.AVG_GEOLOCATION_LAT,
    G.AVG_GEOLOCATION_LNG
FROM OLIST_DB.STAGING.STG_CUSTOMERS C 
LEFT JOIN OLIST_DB.STAGING.STG_GEOLOCATION_AGG G
ON C.CUSTOMER_ZIP_CODE_PREFIX = G.GEOLOCATION_ZIP_CODE_PREFIX;

ALTER TABLE OLIST_DB.ANALYTICS.DIM_CUSTOMERS
ADD CONSTRAINT PK_DIM_CUSTOMERS PRIMARY KEY (CUSTOMER_ID);

CREATE OR REPLACE TABLE OLIST_DB.ANALYTICS.DIM_SELLERS
AS
SELECT
    S.SELLER_ID,
    S.SELLER_ZIP_CODE_PREFIX,
    S.SELLER_CITY,
    S.SELLER_STATE,
    G.AVG_GEOLOCATION_LAT,
    G.AVG_GEOLOCATION_LNG
FROM OLIST_DB.STAGING.STG_SELLERS S 
LEFT JOIN OLIST_DB.STAGING.STG_GEOLOCATION_AGG G
ON S.SELLER_ZIP_CODE_PREFIX = G.GEOLOCATION_ZIP_CODE_PREFIX;

ALTER TABLE OLIST_DB.ANALYTICS.DIM_SELLERS
ADD CONSTRAINT PK_DIM_SELLERS PRIMARY KEY (SELLER_ID);

// creating a function to generate a unique key date from dates date(2026-08-05) => 20260805
CREATE OR REPLACE FUNCTION OLIST_DB.ANALYTICS.TO_DATE_KEY(input_ts TIMESTAMP_NTZ)
RETURNS INT
AS
$$
    TO_NUMBER(TO_CHAR(input_ts, 'YYYYMMDD'))
$$;

//Checking the earliest and latest date available in the dataset to determine approximatively the lenghth of the dim table date as a starter
SELECT MIN(ORDER_PURCHASE_TS), MAX(ORDER_PURCHASE_TS)
FROM OLIST_DB.STAGING.STG_ORDERS;

CREATE OR REPLACE TABLE OLIST_DB.ANALYTICS.DIM_DATE
AS
SELECT
    OLIST_DB.ANALYTICS.TO_DATE_KEY(DATE_DAY) DATE_KEY,
    DATE_DAY,
    YEAR(DATE_DAY) AS YEAR,
    MONTH(DATE_DAY) AS MONTH,
    MONTHNAME(DATE_DAY) AS MONTH_NAME,
    DAY(DATE_DAY) AS DAY,
    DAYOFWEEK(DATE_DAY) AS DAY_OF_WEEK,
    DAYNAME(DATE_DAY) AS DAY_NAME
FROM (
    SELECT DATEADD(DAY , SEQ4(),'2016-09-03') DATE_DAY
    FROM TABLE(GENERATOR(ROWCOUNT => 800))
);

ALTER TABLE OLIST_DB.ANALYTICS.DIM_DATE
ADD CONSTRAINT PK_DIM_DATE PRIMARY KEY (DATE_KEY);


CREATE OR REPLACE TABLE OLIST_DB.ANALYTICS.DIM_PAYMENT_TYPE AS
SELECT
    ROW_NUMBER() OVER (ORDER BY PAYMENT_TYPE) AS PAYMENT_TYPE_KEY,
    PAYMENT_TYPE
FROM (
    SELECT DISTINCT PAYMENT_TYPE
    FROM OLIST_DB.STAGING.STG_ORDER_PAYMENTS
    WHERE PAYMENT_TYPE IS NOT NULL
);

ALTER TABLE OLIST_DB.ANALYTICS.DIM_PAYMENT_TYPE 
ADD CONSTRAINT PK_DIM_PAYMENT_TYPE PRIMARY KEY(PAYMENT_TYPE_KEY);

// fact orders table and its constraints
CREATE OR REPLACE TABLE OLIST_DB.ANALYTICS.FACT_ORDERS
AS
SELECT
    O.CUSTOMER_ID,
    OI.ORDER_ID,
    OI.ORDER_ITEM_ID,
    OI.PRODUCT_ID,
    OI.SELLER_ID,
    OI.PRICE,
    OI.FREIGHT_VALUE,
    O.ORDER_STATUS,
    
    OLIST_DB.ANALYTICS.TO_DATE_KEY(O.ORDER_PURCHASE_TS) AS PURCHASE_DATE_KEY,
    OLIST_DB.ANALYTICS.TO_DATE_KEY(O.ORDER_APPROVED_TS) AS APPROVED_DATE_KEY,
    OLIST_DB.ANALYTICS.TO_DATE_KEY(O.ORDER_DELIVERED_CARRIER_DATE) AS DELIVERED_CARRIER_DATE_KEY,
    OLIST_DB.ANALYTICS.TO_DATE_KEY(O.ORDER_DELIVERED_CUSTOMER_DATE) AS DELIVERED_CUSTOMER_DATE_KEY,
    OLIST_DB.ANALYTICS.TO_DATE_KEY(O.ORDER_ESTIMATED_DELIVERY_DATE) AS ESTIMATED_DELIVERY_DATE_KEY,    
    
    DATEDIFF(day, O.ORDER_ESTIMATED_DELIVERY_DATE, O.ORDER_DELIVERED_CUSTOMER_DATE) AS DELIVERY_DELAY_DAYS


FROM OLIST_DB.STAGING.STG_ORDER_ITEMS OI
JOIN OLIST_DB.STAGING.STG_ORDERS O
ON O.ORDER_ID = OI.ORDER_ID;

ALTER TABLE OLIST_DB.ANALYTICS.FACT_ORDERS 
ADD CONSTRAINT PK_FACT_ORDERS PRIMARY KEY (ORDER_ID ,ORDER_ITEM_ID);

ALTER TABLE OLIST_DB.ANALYTICS.FACT_ORDERS 
ADD CONSTRAINT FK_FACT_ORDERS_CUSTOMERS FOREIGN KEY (CUSTOMER_ID)
REFERENCES OLIST_DB.ANALYTICS.DIM_CUSTOMERS(CUSTOMER_ID); 

ALTER TABLE OLIST_DB.ANALYTICS.FACT_ORDERS 
ADD CONSTRAINT FK_FACT_ORDERS_PRODUCTS FOREIGN KEY (PRODUCT_ID)
REFERENCES OLIST_DB.ANALYTICS.DIM_PRODUCTS(PRODUCT_ID); 

ALTER TABLE OLIST_DB.ANALYTICS.FACT_ORDERS 
ADD CONSTRAINT FK_FACT_ORDERS_SELLERS FOREIGN KEY (SELLER_ID)
REFERENCES OLIST_DB.ANALYTICS.DIM_SELLERS(SELLER_ID); 

ALTER TABLE OLIST_DB.ANALYTICS.FACT_ORDERS 
ADD CONSTRAINT FK_FACT_ORDERS_PURCHASE_DATE FOREIGN KEY (PURCHASE_DATE_KEY)
REFERENCES OLIST_DB.ANALYTICS.DIM_DATE(DATE_KEY); 

ALTER TABLE OLIST_DB.ANALYTICS.FACT_ORDERS 
ADD CONSTRAINT FK_FACT_ORDERS_APPROVED_DATE FOREIGN KEY (APPROVED_DATE_KEY)
REFERENCES OLIST_DB.ANALYTICS.DIM_DATE(DATE_KEY); 

ALTER TABLE OLIST_DB.ANALYTICS.FACT_ORDERS 
ADD CONSTRAINT FK_FACT_ORDERS_DELIVERED_CARRIER_DATE FOREIGN KEY (DELIVERED_CARRIER_DATE_KEY)
REFERENCES OLIST_DB.ANALYTICS.DIM_DATE(DATE_KEY); 

ALTER TABLE OLIST_DB.ANALYTICS.FACT_ORDERS 
ADD CONSTRAINT FK_FACT_ORDERS_DELIVERED_CUSTOMER_DATE FOREIGN KEY (DELIVERED_CUSTOMER_DATE_KEY)
REFERENCES OLIST_DB.ANALYTICS.DIM_DATE(DATE_KEY); 

ALTER TABLE OLIST_DB.ANALYTICS.FACT_ORDERS 
ADD CONSTRAINT FK_FACT_ORDERS_ESTIMATED_DELIVERY_DATE FOREIGN KEY (ESTIMATED_DELIVERY_DATE_KEY)
REFERENCES OLIST_DB.ANALYTICS.DIM_DATE(DATE_KEY); 

// fact payment table and its constraint

CREATE OR REPLACE TABLE OLIST_DB.ANALYTICS.FACT_PAYMENTS AS
SELECT
    p.ORDER_ID,
    p.PAYMENT_SEQUENTIAL,
    pt.PAYMENT_TYPE_KEY,
    p.PAYMENT_INSTALLMENTS,
    p.PAYMENT_VALUE
FROM OLIST_DB.STAGING.STG_ORDER_PAYMENTS p
LEFT JOIN OLIST_DB.ANALYTICS.DIM_PAYMENT_TYPE pt
    ON p.PAYMENT_TYPE = pt.PAYMENT_TYPE;

ALTER TABLE OLIST_DB.ANALYTICS.FACT_PAYMENTS 
ADD CONSTRAINT PK_FACT_PAYMENTS PRIMARY KEY(ORDER_ID, PAYMENT_SEQUENTIAL);

ALTER TABLE OLIST_DB.ANALYTICS.FACT_PAYMENTS 
ADD CONSTRAINT FK_FACT_PAYMENTS_TYPE FOREIGN KEY(PAYMENT_TYPE_KEY)
REFERENCES OLIST_DB.ANALYTICS.DIM_PAYMENT_TYPE(PAYMENT_TYPE_KEY);

// fact reviews and its constraints

CREATE OR REPLACE TABLE OLIST_DB.ANALYTICS.FACT_REVIEWS AS
SELECT
    REVIEW_ID,
    ORDER_ID,
    REVIEW_SCORE,
    OLIST_DB.ANALYTICS.TO_DATE_KEY(REVIEW_CREATION_DATE) AS REVIEW_CREATION_DATE_KEY,
    OLIST_DB.ANALYTICS.TO_DATE_KEY(REVIEW_ANSWER_TS)      AS REVIEW_ANSWER_DATE_KEY,
    REVIEW_COMMENT_TITLE,
    REVIEW_COMMENT_MESSAGE
FROM OLIST_DB.STAGING.STG_ORDER_REVIEWS;

ALTER TABLE OLIST_DB.ANALYTICS.FACT_REVIEWS
ADD CONSTRAINT PK_FACT_REVIEWS PRIMARY KEY (REVIEW_ID);

ALTER TABLE OLIST_DB.ANALYTICS.FACT_REVIEWS
ADD CONSTRAINT FK_FACT_REVIEWS_CREATION_DATE FOREIGN KEY(REVIEW_CREATION_DATE_KEY)
REFERENCES OLIST_DB.ANALYTICS.DIM_DATE(DATE_KEY);

ALTER TABLE OLIST_DB.ANALYTICS.FACT_REVIEWS
ADD CONSTRAINT FK_FACT_REVIEWS_ANSWER_DATE FOREIGN KEY(REVIEW_ANSWER_DATE_KEY)
REFERENCES OLIST_DB.ANALYTICS.DIM_DATE(DATE_KEY);

