
CREATE OR REPLACE FILE FORMAT OLIST_DB.RAW.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('','NULL','null')
    EMPTY_FIELD_AS_NULL = TRUE ;

CREATE OR REPLACE STAGE OLIST_DB.RAW.OLIST_STAGE
    FILE_FORMAT = OLIST_DB.RAW.CSV_FORMAT;

LS @OLIST_DB.RAW.OLIST_STAGE;

SELECT * FROM OLIST_DB.RAW.PRODUCTS 
LIMIT 20;