// the initial view had a scale of 20 and precision 18 but some LNGs had 3 numbers before the . which caused the failed cast 
// fix : scale = 22
WITH CONVERTED 
AS (
    SELECT
        GEOLOCATION_LNG as RAW_LNG,
        TRY_TO_DECIMAL(GEOLOCATION_LNG , 22,18) AS CAST_ATTEMPT
    FROM GEOLOCATION
    )
SELECT *     
FROM CONVERTED
WHERE RAW_LNG IS NOT NULL
AND CAST_ATTEMPT IS NULL;


WITH CONVERTED 
AS (
    SELECT
        PRICE as RAW_PRICE,
        TRY_TO_DECIMAL(PRICE , 10,3) AS CAST_ATTEMPT
    FROM ORDER_ITEMS
    )
SELECT *     
FROM CONVERTED
WHERE RAW_PRICE IS NOT NULL
AND CAST_ATTEMPT IS NULL;

WITH CONVERTED 
AS (
    SELECT
        FREIGHT_VALUE as RAW,
        TRY_TO_DECIMAL(FREIGHT_VALUE , 10, 3) CAST_ATTEMPT
    FROM ORDER_ITEMS
    )
SELECT *     
FROM CONVERTED
WHERE RAW IS NOT NULL
AND CAST_ATTEMPT IS NULL;

WITH CONVERTED 
AS (
    SELECT
        PRODUCT_HEIGHT_CM as RAW_HEIGHT,
        TRY_TO_DECIMAL(PRODUCT_HEIGHT_CM , 8 ,2) PRODUCT_HEIGHT_CM
    FROM PRODUCTS
    )
SELECT *     
FROM CONVERTED
WHERE RAW_HEIGHT IS NOT NULL
AND PRODUCT_HEIGHT_CM IS NULL;

WITH CONVERTED 
AS (
    SELECT
        PRODUCT_PHOTOS_QTY as RAW,
        TRY_CAST(PRODUCT_PHOTOS_QTY AS INT) PRODUCT_PHOTOS_QTY
    FROM PRODUCTS
    )
SELECT *     
FROM CONVERTED
WHERE RAW IS NOT NULL
AND PRODUCT_PHOTOS_QTY IS NULL;

WITH CONVERTED 
AS (
    SELECT
        PRODUCT_PHOTOS_QTY as RAW,
        TRY_CAST(PRODUCT_DESCRIPTION_LENGHT AS INT) PRODUCT_DESCRIPTION_LENGHT
    FROM PRODUCTS
    )
SELECT *     
FROM CONVERTED
WHERE RAW IS NOT NULL
AND PRODUCT_DESCRIPTION_LENGHT IS NULL;


SELECT column_name
FROM OLIST_DB.INFORMATION_SCHEMA.COLUMNS
WHERE table_name = 'ORDERS';

SHOW VIEWS; 

USE SCHEMA OLIST_DB.STAGING;

SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT ORDER_ID) AS distinct_orders
FROM OLIST_DB.STAGING.STG_ORDER_REVIEWS;